### ISSUE TITLE
[Bug] Repeated use triggering Session Expired on Workforce Australia site

### ISSUE THREAD

**Issue by twcau** [zevnda/workforce-mate#3]
### Affected version
1.1.0

### Error message
After submitting one job, URL field doesn't appear on further use. User will re-load the page, and plugin functions as expected initally.

After submitting this next job, user is presented with a Session Expired error from the Workforce Australia website:

![image](https://github.com/user-attachments/assets/c17f71b0-d76b-4dba-a959-744f75e09794)

### Steps to replicate

1. Within Plugin loaded into browser, user navigates to https://www.workforceaustralia.gov.au/individuals/obligations/my-job-search-effort.
2. User selects Add a job.
3. User pastes URL of supported job site into provided field and waits for information to populate.
4. User selects Save.
5. User repeats Steps 1-4.
6. Identified error message displayed.
7. User signs out, then signs back into myGov.
8. User returns to https://www.workforceaustralia.gov.au/individuals/obligations/my-job-search-effort.
9. Job submitted at Step 5 not in lost.

### Workarounds attempted

None identified.

### Debugging information

Observed in Firefox version(s): 127.0 (64-bit), 130.0 (64-bit)
Observed in Microsoft Edge version(s): 129.0.2792.12 (Official build) stable app, beta channel (64-bit)
Observed in OS: Windows 11 Pro, 23H2 Release, OS Build 22635.4145

**Comment by zevnda** [comment]
Thanks again for the issue report!

I believe this is just a my.gov and workforceaus issue. It's been happening on and off since yesterday ([news article](https://thecyberexpress.com/centrelink-outage-hits-app-and-website/)), lots of people complaining about the same thing before I'd even released the extension. Apparently they plan on fixing it over the weekend.

If the issue still persists after than, feel free to reopen this issue by replying to it.
